version: '2'
services:
  mongorsn1:
    container_name: mongors1n1
    image: mongo
    command: mongod --shardsvr --replSet mongors1 --port 27017
    ports:
      - 27017:27017
    expose:
      - "27017"
    environment:
      TERM: xterm
  # mongorsn2:
  #   container_name: mongors2n1
  #   image: mongo
  #   command: mongod --shardsvr --replSet mongors2 --port 27017
  #   ports:
  #     - 27018:27017
  #   expose:
  #     - "27017"
  #   environment:
  #     TERM: xterm
  # mongorsn3:
  #   container_name: mongors3n1
  #   image: mongo
  #   command: mongod --shardsvr --replSet mongors3 --port 27017
  #   ports:
  #     - 27090:27017
  #   expose:
  #     - "27017"
  #   environment:
  #     TERM: xterm

  mongocfg1:
    container_name: mongocfg1
    image: mongo
    command: mongod --configsvr --replSet mongors1conf --port 27017
    environment:
      TERM: xterm
    expose:
      - "27017"
  mongocfg2:
    container_name: mongocfg2
    image: mongo
    command: mongod --configsvr --replSet mongors1conf --port 27017
    environment:
      TERM: xterm
    expose:
      - "27017"
  mongocfg3:
    container_name: mongocfg3
    image: mongo
    command: mongod --configsvr --replSet mongors1conf --port 27017
    environment:
      TERM: xterm
    expose:
      - "27017"

  mongos1:
    container_name: mongos1
    image: mongo
    depends_on:
      - mongocfg1
      - mongocfg2
    command: mongos --configdb mongors1conf/mongocfg1:27017,mongocfg2:27017,mongocfg3:27017 --port 27017 --bind_ip 0.0.0.0
    ports:
      - 27019:27017
    expose:
      - "27017"
  mongos2:
    container_name: mongos2
    image: mongo
    depends_on:
      - mongocfg1
      - mongocfg2
    command: mongos --configdb mongors1conf/mongocfg1:27017,mongocfg2:27017,mongocfg3:27017 --port 27017 --bind_ip 0.0.0.0
    ports:
      - 27020:27017
    expose:
      - "27017"